//ACTION TYPES
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const SINGLE_PRODUCT = 'SINGLE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_QUANITY = 'EDIT_QUANITY';

